In [1]:
import pandas as pd
from src.ingestion.yfinance_loader import fetch_ticker_data
from src.ingestion.utils import save_df_parquet_market_prices

In [4]:
path = "minio_data/raw/market_prices/source=yfinance/asset=IBIT/dt=2025-10-04/part-000.parquet"

df = pd.read_parquet(path)

print(df)

    ('date', '')  ('close', 'ibit')  ('high', 'ibit')  ('low', 'ibit')  \
0     2024-01-11          26.629999         30.000000        26.280001
1     2024-01-12          24.969999         26.410000        24.750000
2     2024-01-16          24.719999         24.862000        24.040001
3     2024-01-17          24.410000         24.559999        24.150000
4     2024-01-18          23.340000         24.469999        23.200001
..           ...                ...               ...              ...
429   2025-09-29          64.970001         65.040001        63.650002
430   2025-09-30          65.000000         65.110001        64.099998
431   2025-10-01          66.739998         67.230003        66.150002
432   2025-10-02          68.769997         68.839996        67.370003
433   2025-10-03          69.809998         70.529999        68.220001

     ('open', 'ibit')  ('volume', 'ibit') ('ticker', '')
0           27.940001            37657300           IBIT
1           26.400000            22991900           IBIT
2           24.700001            15078200           IBIT
3           24.350000            13964500           IBIT
4           24.350000            17823200           IBIT
..                ...                 ...            ...
429         63.720001            51102300           IBIT
430         64.400002            38099900           IBIT
431         66.300003            57783300           IBIT
432         67.760002            62252200           IBIT
433         68.605003            83096100           IBIT

[434 rows x 7 columns]

In [2]:
df = fetch_ticker_data("VT")

df

/home/daniel/fintrack/src/ingestion/yfinance_loader.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start=start)
[*********************100%***********************]  1 of 1 completed

Price,date,close,high,low,open,volume,ticker
Ticker,,vt,vt,vt,vt,vt,
0,2018-01-02,63.701580,63.701580,63.361429,63.395445,1267700,VT
1,2018-01-03,64.135262,64.152273,63.778106,63.778106,768500,VT
2,2018-01-04,64.517914,64.602950,64.415867,64.432871,819400,VT
3,2018-01-05,64.892090,64.909101,64.594460,64.705006,925100,VT
4,2018-01-08,64.960136,64.977148,64.773053,64.832579,723200,VT
...,...,...,...,...,...,...,...
1945,2025-09-29,137.380005,137.600006,137.100006,137.440002,2553600,VT
1946,2025-09-30,137.800003,137.919998,137.009995,137.240005,2948900,VT
1947,2025-10-01,138.509995,138.600006,137.660004,137.660004,2029800,VT
1948,2025-10-02,138.710007,139.039993,138.119995,138.970001,2271200,VT
1949,2025-10-03,139.080002,139.649994,138.809998,139.130005,1940600,VT

In [3]:
path = save_df_parquet_market_prices(df, source="yfinance", asset="VT")